
FROM python:3.10
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./lib/python3.10/site-packages/ /usr/local/lib/python3.10/site-packages/
COPY ./string.py .

# What it does is make a pybrain3 install that uses a modified copy of the library so it works with
# string.py from python3.6
