def simulate_monetary_cascade(initial_capital: float, velocity_factor: float, retention_rate: float, cycles: int):
    """
    Simulates a recursive monetary velocity and feedback cascade.
    
    :param initial_capital: Starting value (e.g., $1.00)
    :param velocity_factor: How many times capital turns over per cycle
    :param retention_rate: Fraction of transaction value that feeds back into the next pool
    :param cycles: Number of iterative cascade loops
    """
    current_pool = initial_capital
    cumulative_throughput = 0.0
    
    print(f"--- Initiating Monetary Cascade ---")
    print(f"Base Capital: ${initial_capital:,.2f} | Velocity: {velocity_factor}x | Retention: {retention_rate * 100}%\n")
    print(f"{'Cycle':<8} | {'Active Pool':<18} | {'Transaction Volume':<20} | {'Cumulative Output':<20}")
    print("-" * 74)
    
    for cycle in range(1, cycles + 1):
        # Transaction volume generated by the current pool moving at a given velocity
        transaction_volume = current_pool * velocity_factor
        cumulative_throughput += transaction_volume
        
        # Feed a portion of the transaction output back into the recursive pool
        current_pool = transaction_volume * retention_rate
        
        print(f"{cycle:<8} | ${current_pool + (transaction_volume * (1 - retention_rate)):<17,.2f} | ${transaction_volume:<19,.2f} | ${cumulative_throughput:<19,.2f}")

    print("-" * 74)
    print(f"Total Cumulative Economic Throughput after {cycles} cycles: ${cumulative_throughput:,.2f}\n")
    return cumulative_throughput

# Execute a 6-cycle cascade starting with a single dollar
if __name__ == "__main__":
    simulate_monetary_cascade(
        initial_capital=1.00, 
        velocity_factor=1.01,   # Each unit moves 2.5 times per cycle
        retention_rate=1.0,    # 40% compounds into the next cycle's pool
        cycles=10_000
    )
